set_property SRC_FILE_INFO {cfile:C:/Users/MuZhi/Desktop/zynq/S9/zynq/06_ip_ram/06_ip_ram.srcs/constrs_1/new/ip_ram.xdc rfile:../../../06_ip_ram.srcs/constrs_1/new/ip_ram.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports rst_n]
