set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN J18 [get_ports rst_n]
set_property PACKAGE_PIN H20 [get_ports key]
set_property PACKAGE_PIN F16 [get_ports led]
